spring:
  application:
    name: myversion
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/Temp
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  datasource:
    url: jdbc:h2:/home/ec2-user/myversiondb
    driver-class-name: org.h2.Driver
    username: mv
    password: mv
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        webAllowOthers: true

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: my-version-user-record-list
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}

server:
    port: 9091